- include_vars: subscription-vault.yml
- redhat_subscription:
    state: present
    username: "{{ rhn_user }}"
    password: "{{ rhn_password }}"
    auto_attach: true
  when: systemid is not defined
  register: subscription_result
  failed_when:
  - subscription_result.failed
  - subscription_result.stderr_lines is not match(".*This system is already registered.*")
  delay: 10
  retries: 6
- redhat_subscription:
    state: present
    username: "{{ rhn_user }}"
    password: "{{ rhn_password }}"
    consumer_id: "{{ systemid }}"
    auto_attach: true
  when: systemid is defined
  register: subscription_result
  failed_when:
  - subscription_result.failed
  - subscription_result.stderr_lines is not match(".*This system is already registered.*")
  delay: 10
  retries: 6
- debug:
    msg: "{{ subscription_result }}"
- shell:
    cmd: subscription-manager refresh
  register: subscription_refresh_result
  failed_when:
  - subscription_refresh_result.rc != 0
  - subscription_refresh_result.stderr_lines is not match(".*Network error, unable to connect to server.*")
- yum:
    update_only: yes
    state: latest 
  register: yum_update_result
  failed_when:
  - yum_update_result.rc != 0
  - yum_update_result.msg is not match (".*All mirrors were tried.*")
- yum:
    name:
      - qemu-kvm
      - libvirt
      - python3-libvirt
      - libguestfs-tools
      - virt-install
      - python3-lxml
      - tuned
    state: installed
  register: yum_install_result
  failed_when:
  - yum_install_result.rc != 0
  - yum_install_result.msg is not match (".*All mirrors were tried.*")
- systemd:
    name: libvirtd
    state: started
    enabled: yes
- systemd:
    name: tuned
    state: started
    enabled: yes
- shell:
    cmd: tuned-adm profile virtual-host
- firewalld:
    zone: public
    port: 5900/tcp
    permanent: yes
    immediate: yes
    state: enabled
