- include_vars: subscription-vault.yml
- redhat_subscription:
    state: present
    username: "{{ rhn_user }}"
    password: "{{ rhn_password }}"
    auto_attach: true
  when: systemid is not defined
  register: subscription_result
  failed_when:
  - subscription_result.failed
  delay: 10
  retries: 6
- redhat_subscription:
    state: present
    username: "{{ rhn_user }}"
    password: "{{ rhn_password }}"
    consumer_id: "{{ systemid }}"
    auto_attach: true
  when: systemid is defined
  register: subscription_result
  failed_when:
  - subscription_result.failed
  delay: 10
  retries: 6
- debug:
    msg: "{{ subscription_result }}"
- shell:
    cmd: subscription-manager refresh
- yum:
    update_only: yes
    state: latest 
- yum:
    name:
      - qemu-kvm
      - libvirt
      - python3-libvirt
      - libguestfs-tools
      - virt-install
      - python3-lxml
      - tuned
    state: installed
- systemd:
    name: libvirtd
    state: started
    enabled: yes
- systemd:
    name: tuned
    state: started
    enabled: yes
- shell:
    cmd: tuned-adm profile virtual-host
- firewalld:
    zone: public
    port: 5900/tcp
    permanent: yes
    immediate: yes
    state: enabled
