- hosts: bastionhost
  environment:
    KUBECONFIG: "{{ ocp_home }}/{{ ocp_type }}/auth/kubeconfig"
    PATH: "{{ ocp_home }}/bin:{{ ansible_env.PATH }}"
  roles:
  - postgresql
  - keycloak
  - role: restricted-olm
    when: olm_install_type is defined and olm_install_type == "disconnected"
