- hosts: bastionhost
  roles:
  - dns
  - ntp
  - tftp
  - dhcp
  - httpd
  - rsyslog
  - haproxy
  - squid
  - nexus
  - nfs
  - kvm
- hosts: kvm
  gather_facts: no
  roles:
  - kvm
- hosts: bastionhost
  roles:
  - upi
