- hosts: bastionhost
  environment:
    KUBECONFIG: "{{ ocp_home }}/{{ ocp_type }}/auth/kubeconfig"
    PATH: "{{ ocp_home }}/bin:{{ ansible_env.PATH }}"
  roles:
  - ocs-remove
- hosts: storage
  gather_facts: false
  roles:
  - ocs-local-storage-clean
