- file:
    path: "{{ ocp_home }}/{{ ocp_type }}"
    state: absent
- file:
    path: "{{ ocp_home }}/{{ ocp_type }}"
    state: directory
    mode: '0755'
- shell: "cat {{ ssh_public_key_file }} | cut -d' ' -f1,2"
  register: ssh_key_output
- set_fact:
    ssh_key: "{{ ssh_key_output.stdout }}"
- shell: echo -n 'admin:admin123' | base64 -w0
  register: nexus_digest_output
  when: ocp_install_type == 'disconnected'
- set_fact:
    nexus_digest: "{{ nexus_digest_output.stdout }}"
  when: ocp_install_type == 'disconnected'
- shell: "openssl s_client -showcerts -servername {{ hostvars[groups['bastionhost'][0]]['ansible_host'] }} -connect {{ hostvars[groups['bastionhost'][0]]['ansible_host'] }}:{{ nexus_docker_secure_port }} </dev/null 2>/dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | csplit -f {{ ocp_home }}/{{ ocp_type }}/additional-trust-bundle -b %02d.crt -z - '/-----BEGIN CERTIFICATE-----/' {1}"
  when: ocp_install_type == 'disconnected'
- shell: "cat {{ ocp_home }}/{{ ocp_type }}/additional-trust-bundle01.crt | sed 's/\\(.*\\)/  \\1/g'"
  register: additional_trustbundle_output
  when: ocp_install_type == 'disconnected'
- set_fact:
    additional_trustbundle: "{{ additional_trustbundle_output.stdout }}"
  when: ocp_install_type == 'disconnected'
- shell:
    cmd: cat {{ ocp_home }}/pull-secrets.json
  register: pull_secrets_output
- set_fact:
    pull_secrets: " {{ pull_secrets_output.stdout }}"
- template:
    src: install-config.yaml.j2
    dest: "{{ ocp_home }}/{{ ocp_type }}/install-config.yaml"
- template:
    src: install-config.yaml.j2
    dest: "{{ ocp_home }}/{{ ocp_type }}/install-config.yaml.ori"
- shell: "{{ ocp_home }}/bin/openshift-install --dir {{ ocp_home }}/{{ ocp_type }} create manifests"
- shell: "sed -i 's/\\(.*\\)mastersSchedulable.*/\\1mastersSchedulable: False/g' {{ ocp_home }}/{{ ocp_type  }}/manifests/cluster-scheduler-02-config.yml"
- shell: "{{ ocp_home }}/bin/openshift-install --dir {{ ocp_home }}/{{ ocp_type }} create ignition-configs"
