- shell: curl --data-urlencode "grant_type=refresh_token" --data-urlencode "client_id=cloud-services" --data-urlencode "refresh_token={{ ocp_offline_access_token }}" https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token | jq -r .access_token
  register: bearer_token_output
  retries: 2
  delay: 10
- set_fact:
    bearer_token: "{{ bearer_token_output.stdout }}"
- shell: "curl -X POST \"https://api.openshift.com/api/accounts_mgmt/v1/access_token\" -H \"accept: application/json\" -H \"Authorization: Bearer {{ bearer_token }}\" -o {{ ocp_home }}/pull-secrets.json"
  retries: 2
  delay: 10
