- name: Create disk for Worker VM
  command: "qemu-img create -f qcow2 -b /var/lib/libvirt/images/rhcos-qemu.qcow2 /var/lib/libvirt/images/{{ item }}.qcow2 {{ worker_node_disksize }}"
  delegate_to: "{{ hostvars[item]['kvm_host'] }}"
  with_items: "{{ groups['workers'] }}"
- shell:
    cmd: virt-install --name {{ item }} --memory {{ worker_node_memory }} --vcpus {{ worker_node_cpu }} --cpu {{ cpu_model }} --disk path=/var/lib/libvirt/images/{{ item }}.qcow2,format=qcow2,bus=virtio,io=threads --hvm --network bridge=br0,mac={{ hostvars[item]['ethernet'] }},model=virtio --boot hd --os-variant rhel8.0 --keymap=de-de --noautoconsole --qemu-commandline="-fw_cfg name=opt/com.coreos/config,file=/var/lib/libvirt/images/worker.ign"
  delegate_to: "{{ hostvars[item]['kvm_host'] }}"
  with_items: "{{ groups['workers'] }}"
