- file:
    path: "{{ ocp_home }}/bin"
    state: directory
    mode: '0755'
- unarchive:
    src: "{{ download_client }}"
    dest: "{{ ocp_home }}/bin"
    remote_src: yes
    creates: "{{ ocp_home }}/bin/oc"
- unarchive:
    src: "{{ download_installer }}"
    dest: "{{ ocp_home }}/bin"
    remote_src: yes
    creates: "{{ ocp_home }}/bin/openshift-install"
