- selinux:
    state: disabled
- file:
    path: /var/www/html/RedHat-CoreOS
    state: directory
- copy:
    src: "{{ ocp_home }}/{{ ocp_type }}/{{ item }}"
    dest: /var/www/html/RedHat-CoreOS
    remote_src: yes
  with_items:
  - master.ign
  - bootstrap.ign
  - worker.ign
- get_url:
    url: "{{ download_kernel }}"
    dest: "/var/www/html/RedHat-CoreOS/vmlinuz-{{ocp_release}}"
  retries: 2
  delay: 3
  register: result
  until: result is succeeded
- file:
    path: /var/www/html/RedHat-CoreOS/vmlinuz
    state: absent
- file:
     src: "/var/www/html/RedHat-CoreOS/vmlinuz-{{ocp_release}}"
     dest: /var/www/html/RedHat-CoreOS/vmlinuz
     state: link
     remote_src: yes
- get_url:
    url: "{{ download_initramfs }}"
    dest: "/var/www/html/RedHat-CoreOS/initramfs.img-{{ocp_release}}"
  retries: 2
  delay: 3
  register: result
  until: result is succeeded
- file:
    path: /var/www/html/RedHat-CoreOS/initramfs.img
    state: absent
- file:
     src: "/var/www/html/RedHat-CoreOS/initramfs.img-{{ocp_release}}"
     dest: /var/www/html/RedHat-CoreOS/initramfs.img
     state: link
     remote_src: yes
- get_url:
    url: "{{ download_image_metal }}"
    dest: /var/www/html/RedHat-CoreOS/rhcos-{{ ocp_release }}-metal.raw.gz
  retries: 2
  delay: 3
  register: result
  until: result is succeeded
- file:
    path: /var/www/html/RedHat-CoreOS/rhcos-metal.raw.gz
    state: absent
- file:
     src: /var/www/html/RedHat-CoreOS/rhcos-{{ ocp_release }}-metal.raw.gz
     dest: /var/www/html/RedHat-CoreOS/rhcos-metal.raw.gz
     state: link
     remote_src: yes
- file:
    path: /var/www/html/RedHat-CoreOS/rhcos-metal.raw.gz.sha256sum
    state: absent
- shell: sha256sum /var/www/html/RedHat-CoreOS/rhcos-{{ ocp_release }}-metal.raw.gz > /var/www/html/RedHat-CoreOS/rhcos-{{ ocp_release }}-metal.raw.gz.sha256sum
- file:
    src: /var/www/html/RedHat-CoreOS/rhcos-{{ ocp_release }}-metal.raw.gz.sha256sum
    dest: /var/www/html/RedHat-CoreOS/rhcos-metal.raw.gz.sha256sum
    state: link
    remote_src: yes
- file:
    path: /var/www/html
    mode: g+r
    recurse: yes
- shell: chcon -Rv --type=httpd_t /var/www/html
- selinux:
    policy: targeted
    state: enforcing
