- name: Include global variables
  include_vars: ../../common/defaults/main.yml
- name: Include variables from Nexus
  include_vars: ../../nexus/defaults/main.yml
- name: Cleanup known_hosts
  import_tasks: clean_known_hosts.yml
- name: Download OCP 4 Clients and Installer
  import_tasks: install_clients.yml
- name: Create OCP 4 Pull-Secrets
  import_tasks: create_pull_secrets.yml
- name: Create OCP 4 UPI intallation configuration for Bare Metal
  import_tasks: create_installer_config.yml
- name: Upload OCP 4 UPI installation assets
  import_tasks: install_installer_assets.yml
- name: Mirror OCP 4 Images for Disconnected Install
  import_tasks: mirror_ocp_images.yml
  when: ocp_install_type is defined and ocp_install_type == 'disconnected'
- name: Remove all nodes
  import_tasks: ../../kvm/tasks/remove_all_nodes.yml
- name: Initialize Bootstrap nodes
  import_tasks: initialize_bootstrap_nodes.yml
- name: Initialize Infra Nodes
  import_tasks: initialize_infra_node.yml
- name: Wait for Bootstrap completion
  import_tasks: wait_for_bootstrap_completion.yml
- name: Setup image-registry storage
  import_tasks: registry_storage.yml
- name: Cleanup known_hosts
  import_tasks: clean_known_hosts.yml
- name: Shutdown Bootstrap Node
  import_tasks: shutdown_bootstrap_node.yml
- name: Initialize Worker Nodes
  import_tasks: initialize_worker_node.yml
- name: Wait for Installation completion
  import_tasks: wait_for_installation_completion.yml
