- selinux:
    state: disabled
  delegate_to: "{{ item }}"
  with_items: "{{ groups['kvm'] }}"
- get_url:
    url: "http://{{ hostvars[groups['bastionhost'][0]]['ansible_host'] }}/RedHat-CoreOS/rhcos-qemu.qcow2.gz"
    dest: /var/lib/libvirt/images/rhcos-qemu.qcow2.gz
    remote_src: yes
  delegate_to: "{{ item }}"
  with_items: "{{ groups['kvm'] }}"
- shell:
    cmd: gunzip /var/lib/libvirt/images/rhcos-qemu.qcow2.gz
    creates: /var/lib/libvirt/images/rhcos-qemu.qcow2
  delegate_to: "{{ item }}"
  with_items: "{{ groups['kvm'] }}"
- get_url:
    url: "http://{{ hostvars[groups['bastionhost'][0]]['ansible_host'] }}/RedHat-CoreOS/master.ign"
    dest: /var/lib/libvirt/images/master.ign
    remote_src: yes
  delegate_to: "{{ item }}"
  with_items: "{{ groups['kvm'] }}"
- get_url:
    url: "http://{{ hostvars[groups['bastionhost'][0]]['ansible_host'] }}/RedHat-CoreOS/bootstrap.ign"
    dest: /var/lib/libvirt/images/bootstrap.ign
    remote_src: yes
  delegate_to: "{{ item }}"
  with_items: "{{ groups['kvm'] }}"
- get_url:
    url: "http://{{ hostvars[groups['bastionhost'][0]]['ansible_host'] }}/RedHat-CoreOS/worker.ign"
    dest: /var/lib/libvirt/images/worker.ign
    remote_src: yes
  delegate_to: "{{ item }}"
  with_items: "{{ groups['kvm'] }}"
- shell: chcon -Rv --type=virt_image_t /var/lib/libvirt/images
  delegate_to: "{{ item }}"
  with_items: "{{ groups['kvm'] }}"
- selinux:
    policy: targeted
    state: enforcing  
  delegate_to: "{{ item }}"
  with_items: "{{ groups['kvm'] }}"
