- set_facts:
    bastion_host: "{{ hostvars[groups['bastionhost'][0]]['ansible_host'] }}:{{ nexus_port }}"
- name: Change admin password
  shell:
    cmd: curl -X PUT -u "admin:$(cat /mnt/detached-storage/sonatype-work/nexus3/admin.password)" "http://{{ bastion_host }}/service/rest/beta/security/users/admin/change-password" -H "accept: application/json" -H "Content-Type: text/plain" -d "admin123"
- name: Create Blob-Storage
  shell:
    cmd: curl -X POST - "admin:admin123" "http://{{ bastion_host }}/service/rest/beta/blobstores/file" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"path\": \"/mnt/detached-storage/nexus-blob\", \"name\": \"ocp4labs\"}
- name: Create Docker-Repos
  shell:
    cmd: curl -X POST -u "admin:admin123" "http://{{ bastion_host }}/service/rest/beta/repositories/docker/hosted" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"name\": \"ocp4labs\", \"online\": true, \"storage\": { \"blobStoreName\": \"default\", \"strictContentTypeValidation\": true, \"writePolicy\": \"redeploy\" }, \"docker\": { \"v1Enabled\": false, \"forceBasicAuth\": true, \"httpPort\": 5000, \"httpsPort\": {{ nexus_docker_port }} }}"
