- name: Create etc folder
  file:
    path: /opt/sonatype-work/nexus3/etc
    state: directory
- name: Copy nexus.properties
  copy:
    src: nexus.properties
    dest: /opt/sonatype-work/nexus3/etc
- name: Change Nexus install directory ownershirp
  file:
    path: /opt/nexus
    owner: nexus
    group: nexus
    recurse: yes
    state: directory
- name: Copy jetty-https.xml
  copy:
    src: jetty-https.xml
    dest: /opt/nexus/etc/jetty
- name: Copy nexus.jvmoption
  template:
    src: nexus.vmoptions.j2
    dest: /opt/nexus/bin/nexus.vmoptions
- name: Change Nexus working directory ownership
  file:
    path: /opt/sonatype-work
    owner: nexus
    group: nexus
    recurse: yes
    state: directory
