- name: Gather services facts
  service_facts:
- name: Include Nexus tasks
  include_tasks: setup_nexus.yml
  when: ocp_install_type == 'disconnected' and not ansible_facts.services['nexus.service'].state == 'running'
