- shell: "nmcli con mod \"System enp1s0\" ipv4.dns \"{{ hostvars[groups['bastionhost'][0]]['ansible_host'] }} {{ dhcp_public_dns }}\" ipv4.dns-search {{ ocp_cluster_name }}.{{ ocp_cluster_domain_name }}"
- lineinfile:
    path: /etc/hosts
    line: "{{ hostvars[item]['ansible_host'] }} {{ hostvars[item]['inventory_hostname'] }}.{{ ocp_cluster_name }}.{{ ocp_cluster_domain_name }} {{ hostvars[item]['inventory_hostname'] }}"
    state: present
  with_flattened:
  - "{{ groups['bastionhost'] }}"
  - "{{ groups['kvm'] }}"
  - "{{ groups['masters'] }}"
  - "{{ groups['workers'] }}"
- name: Install dnsmasq
  yum:
    name: dnsmasq
    state: present
- name: Create dnsmasq config
  template:
    src: "dnsmasq-ocp.j2"
    dest: "/etc/dnsmasq.d/{{ ocp_cluster_name }}.conf"
- name: restart dnsmasq
  service:
    name: dnsmasq
    state: restarted
- name: Enable DNS Port (TCP Port 53, public zone) firewalld
  firewalld:
    port: "53/tcp"
    zone: public
    permanent: yes
    state: enabled
- name: Enable DNS Port (UDP Port 53, public zone) firewalld
  firewalld:
    port: "53/udp"
    zone: public
    permanent: yes
    state: enabled
