- stat: path=/var/www/html/RedHat-RHEL/8.1/images/pxeboot/initrd.img
  register: initrd_stat_result
- name: Mount RHEL 8.1 ISO and copy contents to HTTP server
  import_tasks: provide_iso.yml
  when: not initrd_stat_result.stat.exists
